# Generated by Django 4.2.16 on 2024-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_patient_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('test_name', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('test_result', models.TextField()),
                ('remark', models.TextField()),
                ('crp', models.IntegerField()),
                ('wbc', models.IntegerField()),
                ('hemoglobin', models.IntegerField()),
                ('platelet', models.IntegerField()),
                ('blood_glucose', models.FloatField()),
                ('bilirubin', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('potassium', models.IntegerField()),
            ],
        ),
    ]
