# Generated by Django 4.2.16 on 2024-11-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.IntegerField()),
                ('dob', models.DateField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('room_charge', models.IntegerField()),
                ('doctor_charge', models.IntegerField()),
                ('laboratory_charge', models.IntegerField()),
                ('medication', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
