# Generated by Django 4.2.16 on 2024-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_doctor_register_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('staff_type', models.CharField(max_length=100)),
                ('staff_department', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Media/Staff Image/')),
            ],
        ),
    ]
