# Generated by Django 4.2.16 on 2024-11-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_add_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_staff',
            new_name='add_staff_data',
        ),
    ]
