# Generated by Django 4.2.16 on 2024-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_first_name_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, default='/static/image/', null=True, upload_to='Media/Documents/'),
        ),
    ]
