# Generated by Django 4.2.16 on 2024-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('symptoms', models.TextField()),
                ('medical_history', models.TextField()),
                ('image', models.FileField(upload_to='Image/Patient Image/')),
            ],
        ),
    ]
