# Generated by Django 4.2.16 on 2024-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_registerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='image',
            field=models.FileField(default='/static/image/john.jpg', upload_to='Image/Patient Image/'),
        ),
    ]
