# Generated by Django 4.2.16 on 2024-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdata',
            name='image',
            field=models.ImageField(upload_to='Media/Patient Image/'),
        ),
    ]
