# Generated by Django 4.2.16 on 2024-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_contact_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerdata',
            new_name='appointment_data',
        ),
    ]
