# Generated by Django 4.2.16 on 2024-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_registerdata_appointment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor_name', models.CharField(max_length=50)),
                ('your_name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('rating', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
    ]
